

logging:
  level:
    ROOT: INFO
    com.poc.testoffert: INFO
    org.mongodb: WARN
    io.undertow: WARN
server:
  port: 8089

spring:
  config:
    activate:
      on-profile: prod

  data:
    mongodb:
      host: testtoffer-mongodb
      port: 27017
      database: testoffertdbprod
      username: root
      password: root
      auto-index-creation: true
      authentication-database: admin