

logging:
  level:
    ROOT: DEBUG
    com.poc.testoffert: DEBUG
    org.mongodb: INFO
    io.undertow: INFO

server:
  port: 8089

spring:
  config:
    activate:
      on-profile: dev


  data:
    mongodb:
      host: localhost
      port: 27017
      database: testoffertdbdev
      username: root
      password: root
      auto-index-creation: true
      authentication-database: admin

