version: '2'
services:
  testtoffer-app:
    image: leonmofor/testoffer:00
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_HOST=192.168.1.8
      - SPRING_DATA_MONGODB_PORT=27018
      - SPRING_DATA_MONGODB_DATABASE=testoffertdbprod
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=root
      #- SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE=admin
      - SLEEP_TIME=30 # gives time for other services to boot before the application
    ports:
      - 8089:8089
  testtoffer-mongodb:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    extends:
      file: mongodb.yml
      service: testtoffer-mongodb

